name: news-to-sheets

on:
  schedule:
    # GitHub Actions는 UTC 기준 → KST(UTC+9) 10/12/14/16/18시는 UTC 01/03/05/07/09
    - cron: "0 1,3,5,7,9 * * *"
  workflow_dispatch: {}

concurrency:
  group: news-to-sheets
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    # ⬇️ 레포 Variables 또는 하드코딩 중 택1
    env:
      SPREADSHEET_ID: ${{ vars.SPREADSHEET_ID }}   # 예: 1QP56lm5kPBdsUhrgcgY2U-JdmukXIkKCSxefd1QExKE
      SHEET_NAME:     ${{ vars.SHEET_NAME }}       # 예: 압구정_뉴스

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser gspread google-auth

      # ✅ Secret에 저장된 서비스계정 JSON "원문"을 파일로 저장
      - name: Write service account JSON
        run: |
          cat > service_account.json <<'JSON'
          ${{ secrets.SERVICE_ACCOUNT_JSON }}
          JSON

      # (선택) 설정 값 확인용 — 민감정보 아님
      - name: Print env
        run: echo "ID=${SPREADSHEET_ID}  SHEET=${SHEET_NAME}"

      - name: Run collector
        run: python news.py
