name: news-to-sheets

on:
  schedule:
    - cron: "0 1,3,5,7,9 * * *"     # 10·12·14·16·18 KST
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SPREADSHEET_ID: "1QP56lm5kPBdsUhrgcgY2U-JdmukXIkKCSxefd1QExKE"
      SHEET_NAME: "압구정_뉴스"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser gspread google-auth

      - name: Run collector
        run: |
          python news.py
