name: news-to-sheets

on:
  schedule:
    # GitHub Actions는 UTC 기준 → KST(UTC+9) 10/12/14/16/18시는 UTC 01/03/05/07/09
    - cron: "0 1,3,5,7,9 * * *"
  workflow_dispatch: {}

concurrency:
  group: news-to-sheets
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    # 레포 Variables로 관리하는 것을 권장 (Settings → Secrets and variables → Actions → Variables)
    env:
      SPREADSHEET_ID: ${{ vars.SPREADSHEET_ID }}   # 1QP56lm5kPBdsUhrgcgY2U-JdmukXIkKCSxefd1QExKE
      SHEET_NAME:     ${{ vars.SHEET_NAME }}       # 압구정_뉴스
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser gspread google-auth

      # ✅ b64 없이: Secret에 저장한 서비스계정 JSON 원문을 파일에 씁니다.
      - name: Write service account JSON
        run: |
          cat > service_account.json <<'JSON'
          ${{ secrets.SERVICE_ACCOUNT_JSON }}
          JSON

      - name: Run collector
        run: python news.py
